### PR TITLE
location search functional, models updated

### PR DESCRIPTION
**Pull request by digitalfences**
- Related Issue (include '#'):

- Description of changes made:

- Is the feature complete/bug resolved/etc..:

- Any known bugs/strange behavior:

- Is there specific feedback you would like on these changes:

- Screenshot(s):

### CODE REVIEW

**Comment by digitalfences** [comment]
This should remove errors when running server

**Comment by digitalfences** [comment]
@rc1336  This change was only to comment out the changes I had unintentionally made to the code. The error you're throwing I don't recognize

**Comment by rc1336** [comment]
@digitalfences I resend that last comment. I need you to resolve the merge conflicts on this branch and then I will approve this.

**Comment by digitalfences** [comment]
@rc1336 No merge conflicts detected and routes functional.

**Comment by clarknoah** [comment]
@digitalfences I get the following errors when I access your repo and run the server: 


  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/clarknoah/Development/ga/sei/final_project/CoTripper_deployment_test/CoTrip/api/trip/urls.py", line 21
    path('activity/<int:pk>', ActivityDetail.as_view(), name='activity_detail')
       ^

Please correct this bug and ensure you have the latest develop code in you branch, thanks brother!

**Comment by clarknoah** [comment]
@digitalfences I get the following error when I run `migrate`
Applying trip.0007_auto_20200513_1918...Traceback (most recent call last):
  File "/Users/clarknoah/.local/share/virtualenvs/api-zCDy4SHN/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: ""

**Comment by digitalfences** [comment]
@rc1336 @clarknoah 
necessary to run 
`$ psql -U postgres -f settings.sql`
to ensure that existing data is dropped.
then run 
`# Migrate the database:
python3 manage.py migrate --settings api.settings.local

# Seed Database with fixtures data
python3 manage.py loaddata community accounts trip forum --settings api.settings.local

# Run the backend development server:
python3 manage.py runserver --settings api.settings.local`

to reseed database and runserver. 
Route can be tested at locations/bystate
filter will require a code in the form of the state's usual abbreviation (ex. CA)
all locations in that state will be returned from the database

**Pull request merged**
