### PR TITLE
Dami feature forum page

### PR DESCRIPTION
**Pull request by dakom0**
- Related Issue (include '#'):
Issue #568 

- Description of changes made:
Made a mockup of the social forum page

- Is the feature complete/bug resolved/etc..:

- Any known bugs/strange behavior:
The follow button needs to store data to change from 'follow' to 'followed'.

- Is there specific feedback you would like on these changes:
Needs props to be passed in from a user or it can be hardcoded.

- Screenshot(s):
Screen Shot 2020-05-13 at 8 45 33 PM

### CODE REVIEW

**Comment by clarknoah** [comment]
@dakom0 this looks Fantastic, there a few things I'd like you to add: 
1. After clicking on the "Follow #hashtag", and confirming you want to follow it, the modal should close, and the yellow button should be replaced with a pink button that says "followed". 
2. Add a media query for mobile so that if the screen shrinks enough width wise, the "media images" stack below the forum pasts. 

This looks really amazing brother! Do that and I'll close this out, great job man!

**Comment by clarknoah** [comment]
@dakom0 I did a merge, please correct the conflict and then I will merge it!

**Comment by dakom0** [comment]
@clarknoah @rc1336

**Comment by rc1336** [comment]
@dakom0 This has been merged. Great job

**Pull request merged**
