### PR TITLE
Andrew forum page feature branch 

### PR DESCRIPTION
**Pull request by Athly23**
- Related Issue (include '#'):
issue 562
- Description of changes made:
made the static front forum page
- Is the feature complete/bug resolved/etc..:
no backend integration 
- Any known bugs/strange behavior:
no known bugs at the moment 
- Is there specific feedback you would like on these changes:

- Screenshot(s):

### CODE REVIEW

**Comment by Athly23** [comment]
> When I go to the `/forum-page` I get routed to the `Book a Trip` page. Can you go back and double-check this. Also, Your branch has merge conflicts, I need you to remedy those before we can merge this into the develop branch. @Athly23

@rc1336  @clarknoah the changes has been made and forum routes work as well as all merge conflict has been fixed.

**Comment by clarknoah** [comment]
@Athly23 the "Previous Trips" button should not be there per the Figma Mockup, please correct that so I can merge this!

**Comment by Athly23** [comment]
@rc1336 @clarknoah I removed the previous trip button

**Comment by clarknoah** [comment]
dope, this has been merged!

**Pull request merged**
