### PR TITLE
Header is fixed

### PR DESCRIPTION
**Pull request by rmfortes**
- Related Issue (include '#'): 553

- Description of changes made: 

1. When each link is clicked, the user is routed to the appropriate page. (As it is now, 'forum', 'directory', and 'community' will not render because those pages don't exist in my code; once Scott, Dami, and Andrew's code is merged, they will.) 
2. Previously, the drop-down menu was rendering when the user hovered over every component. Now, it only renders when the user hovers over 'community,' as it should. 
3. The purple arrow now follows the user's behavior and renders under the appropriate clicked link. Functionality for that purple arrow lives in the documents for each individual page; once Scott and Dami's code is merged into the project, the purple arrow will follow whatever page the user is on. The purple arrow should not be visible at all when the user is at "/home". 

- Is the feature complete/bug resolved/etc..: Yes! But there are still some missing features that I did not sign up to build. More details below. 

- Any known bugs/strange behavior: The chat bubble & search bar to the far right do not yet render any features.

### CODE REVIEW

**Comment by rc1336** [comment]
Hey @rmfortes, everything looks good to me. The only question I have is with the number 3. I do not see a `purple arrow`. Can you give me a bit more clarification on that?

**Comment by rc1336** [comment]
Also, your branch has two merge conflicts. Can you please resolve those?

**Comment by rmfortes** [comment]
Fixed! Thanks @clarknoah and @rc1336

**Comment by rmfortes** [comment]
@rc1336 @clarknoah resubmitted; apologies for the last submish!

**Comment by clarknoah** [comment]
@rmfortes reviewing now!

**Comment by clarknoah** [comment]
@rmfortes great stuff, I'm closing out this issue!

**Pull request merged**
