### PR TITLE
Edit Profile Permission/Authentication Settings

### PR DESCRIPTION
**Pull request by arjunrawal07**
- Related Issue (include '#'):
#588 
- Description of changes made:

- Is the feature complete/bug resolved/etc..:
Yes.  The feature now allows the user to edit only their own profile.
- Any known bugs/strange behavior:
No. I tested in Postman and I successfully able to update only the profile account I made, and unable to edit other profile accounts (from the seed data).
- Is there specific feedback you would like on these changes:

- Screenshot(s):

### CODE REVIEW

**Comment by rc1336** [comment]
Hey @arjunrawal07, could you please provide me the Postman Request you used to test this? I would like to use them on this end to verify everything is working.

**Comment by arjunrawal07** [comment]
@rc1336 Of course. Please see below for a dummy profile I created.

Before submitting the PUT request, you have to create a profile, then login.  When submitting the PUT request to update your profile, store the token given to you after logging in as an Authorization Header in Postman.

Request Method: PUT
Endpoint(insert primary key, or id, of Profile at end of url): http://localhost:8000/posts/7
Body: {
 {
        "user": 7,
        "topics": [],
        "hashtags": [],
        "image": "www",
        "first_name": "Testing",
        "last_name": "Update Profile Info",
        "city_of_residence": null,
        "age": null,
        "dream_destination": "",
        "bio": "",
        "activities": [],
        "events": [],
        "connections": [],
        "social_media": []
    }
}

**Comment by clarknoah** [comment]
@arjunrawal07 you've got a conflict in pipfile.lock, fix this so I can work on merging it!

**Comment by arjunrawal07** [comment]
@clarknoah I believe I have resolved the conflict.

**Comment by rc1336** [comment]
This looks great @arjunrawal07! Merging this in now.

**Pull request merged**
